# Generated by Django 3.1.2 on 2020-10-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
