# Generated by Django 2.2.6 on 2019-11-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjangoBlog', '0002_auto_20191016_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Image'),
        ),
    ]
